// tailwind.config.js
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        orbitron: ["'Orbitron'", "sans-serif"],
      },
      fontSize: {
        "7xl": "5rem",
        "8xl": "6rem",
      },
      maxWidth: {
        "screen-3xl": "1920px",
      },
    },
  },
  safelist: [
    // Responsive sizes
    "w-2/3",
    "w-full",
    "h-screen",
    "h-full",
    "min-h-screen",
    "h-[375px]",
    "xl:h-[475px]",
    "xl:h-[500px]",
    "max-w-[160px]",
    "xl:max-w-[190px]",
    "xl:max-w-5xl",
    "max-w-4xl",
    "xl:min-w-[190px]",
    "min-w-[160px]",
    "w-[calc(100%-160px)]",

    // Typography
    "text-3xl",
    "text-4xl",
    "text-5xl",
    "text-6xl",
    "text-7xl",
    "text-sm",
    "text-base",
    "text-lg",
    "text-xs",
    "text-white",
    "text-black",
    "text-yellow-500",
    "text-blue-500",
    "text-red-500",
    "text-gray-300",

    // Borders, backgrounds, z-index, spacing
    "rounded-md",
    "rounded-lg",
    "border",
    "border-white",
    "bg-white",
    "bg-opacity-20",
    "bg-gray-100",
    "bg-gray-300",
    "bg-cover",
    "bg-center",
    "bg-no-repeat",
    "backdrop-blur-md",
    "z-[1000]",
    "z-[500]",
    "z-10",
    "z-50",
    "z-[2000]",

    // Flex/grid helpers
    "flex",
    "items-center",
    "justify-center",
    "items-start",
    "justify-between",
    "justify-end",
    "flex-wrap",
    "gap-2",
    "gap-3",
    "gap-4",
    "xl:gap-4",
    "pb-4",
    "mt-2",
    "xl:mt-4",
    "mb-3",
    "mb-6",
    "px-2",
    "xl:px-4",

    // Custom backgrounds used in code
    "bg-[url('/assets/earth.jpg')]",
    "bg-[url('/assets/desert.jpg')]",
    "bg-[url('/assets/amalfi-night.jpg')]",
    "bg-[url('/assets/bridge.jpg')]",
    "bg-[url('/assets/cave.jpg')]",
    "bg-[url('/assets/waterfall.jpg')]",
  ],
};
